Version 5
mailjet/mailjet-apiv3-nodejs pull request #209
Opened 2022-06-22 15:55 UTC by scroll17

2022-06-23 09:04 UTC, olexandr-mazepa requested changes

2022-06-23 09:36 UTC, scroll17 commented on lib/request/index.ts
> +  ): Promise<IAPIResponse<TBody> | IAPILocalResponse<TBody, TParams>> {
Please, look above and you will see that in this code exist two TypeScript signatures that provide method overloading (Polymorphism), and the last method (third) is a method implementation. Users can pass the `performAPICall` param and receive a local response signature instead of a real request.

Yeah, I can add comments there if you think that will be useful.
---

About "two different parameters" - yeah, I thought about it, but we have three parameters in the options and for this reason, we need to add three parameters for the method but for this way in some cases users should be passed `undefined` for **first** or **second** before he can pass some values for third param (`performAPICall`). 

But I have an idea, we can create methods for setting the `performAPICall` param for all `class Request` but if we made it, we will lose the Polymorphism, and users will always check the response type (it's a local response or it's real request - `IAPILocalResponse<TBody, TParams>` or `IAPIResponse<TBody>`).

2022-06-23 09:39 UTC, scroll17 commented on dist/declarations/client/index.d.ts
> +        headers?: import("axios").AxiosRequestHeaders | undefined;
Yes, I think that we can move these imports to the top but only manually because these `.d.ts` files are a result of the work `TypeScript` and `Webpack`.

2022-06-23 09:53 UTC, olexandr-mazepa commented on dist/declarations/client/index.d.ts
> +        headers?: import("axios").AxiosRequestHeaders | undefined;
Oh i didn't notice that this is d.ts file, if in main file imports are in the top than this is fine

2022-06-23 10:02 UTC, scroll17 commented on dist/declarations/client/index.d.ts
> +        headers?: import("axios").AxiosRequestHeaders | undefined;
Yes, of course, all files into `lib` folder honor the agreement about import at the top of the file, and these imports are grouped by type: `external modules`, `utils`, `lib`, e.t.

2022-06-24 09:09 UTC, olexandr-mazepa approved these changes

2022-06-24 10:13 UTC, merged